import type { Metadata, Viewport } from "next";
import { Work_Sans } from "next/font/google";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { ThemeProvider } from "@/components/theme-provider" 
import { Toaster } from "@/components/ui/sonner"; 
import { ReactQueryDevtools } from '@tanstack/react-query-devtools' 
import "./globals.css";

const work_sans = Work_Sans({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });

export const metadata: Metadata = {
  title: "PawPrint",
  description: "Generated by create next app"
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { 
  return (
    <ReactQueryClientProvider>
      <html lang="en" suppressHydrationWarning>   
        <body className={`${work_sans.className} antialiased`} >  
          <ThemeProvider
            attribute="class" 
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >       
            {children}
          </ThemeProvider>   
          <Toaster /> 
        </body> 
      </html>
      <ReactQueryDevtools initialIsOpen={true} /> 
    </ReactQueryClientProvider>
  );
}